import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const html = readFileSync("resource-library.html", "utf8");
const script = readFileSync("src/client/resource-library.js", "utf8");
const styles = readFileSync("styles.css", "utf8");
const filterForm = html.match(/<form id="resourceEligibilityForm"[\s\S]*?<\/form>/)?.[0] || "";
const toolbar = html.match(/<div class="resource-toolbar">[\s\S]*?<\/div>\s*<\/div>/)?.[0] || "";

assert.match(html, /class="[^"]*brand-page-header[^"]*"/, "Resource page should use the shared brand header.");
assert.ok(html.includes('href="./index.html"'), "Resource page must retain access to the planning workspace.");
assert.ok(filterForm.includes('id="resourceSearch"'), "搜索输入框应位于我的可参与条件区域中。");
assert.ok(filterForm.includes('id="resourceSearchField"'), "资源库应提供跨标签通用搜索框。");
assert.ok(html.includes('id="resourceFilterSummary"'), "资源库应显示当前筛选摘要。");
assert.ok(html.includes('id="resourceFilterPills"'), "资源库应把已选筛选条件显示为 pills。");
assert.ok(html.includes('id="resourceResultSummary"'), "资源库结果区顶部应显示当前结果数量。");
assert.ok(html.includes('id="toggleResourceFilters"'), "资源库高级筛选应可以折叠展开。");
assert.ok(filterForm.includes('class="resource-filter is-collapsed"'), "资源库高级筛选应默认折叠，避免表单占据首屏。");
assert.ok(filterForm.includes('id="resourceSchoolContext"'), "可参与条件应允许选择当前就读体系。");
assert.ok(filterForm.includes("中国大陆高中在读"), "就读体系应明确覆盖中国大陆高中学生。");
assert.ok(filterForm.includes('id="resourceEligibilityFields"'), "项目资源应保留国籍、身份、就读体系和参与方式筛选区。");
assert.ok(filterForm.includes('id="activityFilterFields"'), "课外活动库应提供独立筛选区。");
assert.ok(filterForm.includes('id="activityCommonAppType"'), "课外活动库筛选应包含 Common App 类型下拉。");
assert.ok(filterForm.includes('id="activityMajorDirection"'), "课外活动库筛选应包含专业方向输入。");
assert.ok(filterForm.includes('id="journalFilterFields"'), "国际期刊汇总应提供独立筛选区。");
assert.ok(filterForm.includes('id="journalDirection"'), "国际期刊汇总应允许选择论文方向。");
assert.ok(filterForm.includes('id="journalDirectionToggle"'), "论文方向应使用可控的向下展开按钮。");
assert.ok(filterForm.includes('id="journalDirectionMenu"'), "论文方向应使用页面内下拉菜单而非浏览器原生弹层。");
assert.ok(filterForm.includes('data-journal-direction-combobox'), "论文方向下拉应有独立 combobox 容器。");
assert.ok(html.includes("styles.css?v=20260605-ui"), "资源库页面应刷新 CSS 版本以避免旧按钮样式缓存。");
assert.ok(filterForm.includes('id="journalIndexDatabase"'), "国际期刊汇总应允许选择检索库要求。");
assert.ok(filterForm.includes("检索库要求"), "国际期刊筛选应使用用户指定的检索库口径。");
assert.ok(!toolbar.includes('id="resourceSearch"'), "搜索输入框不应继续位于独立资源工具栏中。");
assert.ok(html.includes('id="researchProjectTab"'), "应提供实习/科研库标签。");
assert.ok(html.includes('id="researchProjectLibrary"'), "应提供实习/科研库内容面板。");
assert.ok(html.includes("实习/科研库"), "标签应使用用户指定的名称。");
assert.ok(html.includes('id="extracurricularActivityTab"'), "应提供课外活动库标签。");
assert.ok(html.includes('id="extracurricularActivityLibrary"'), "应提供课外活动库内容面板。");
assert.ok(html.includes("课外活动库"), "资源库应新增课外活动库入口。");
assert.ok(html.includes('id="internationalJournalTab"'), "应提供国际期刊汇总标签。");
assert.ok(html.includes('id="internationalJournalLibrary"'), "应提供国际期刊汇总内容面板。");
assert.ok(html.includes("国际期刊汇总"), "资源库应新增国际期刊汇总入口。");
assert.ok(html.includes('id="loadMoreResources"'), "资源库应提供加载更多按钮。");
assert.ok(script.includes('fetch("./data/extracurricular-activities.md")'), "前端脚本应加载由 docx 转出的课外活动库 RAG 数据。");
assert.ok(script.includes('fetch("./data/international-journals.md")'), "前端脚本应加载由 docx 转出的国际期刊 RAG 数据。");
assert.ok(script.includes("parseExtracurricularActivitiesMarkdown"), "前端脚本应使用课外活动库解析器。");
assert.ok(script.includes("parseInternationalJournalsMarkdown"), "前端脚本应使用国际期刊解析器。");
assert.ok(script.includes("filterInternationalJournals"), "前端脚本应按论文方向和检索库筛选国际期刊。");
assert.ok(script.includes("openJournalDirectionMenu"), "论文方向菜单应由前端控制并固定向下展开。");
assert.ok(script.includes("updateFilterMode"), "切换到课外活动库时应切换筛选方式。");
assert.ok(script.includes("populateActivityFilterOptions"), "课外活动库应从 RAG 数据生成 Common App 类型和专业方向筛选项。");
assert.ok(script.includes("populateJournalFilterOptions"), "国际期刊汇总应从 RAG 数据生成论文方向和检索库筛选项。");
assert.ok(script.includes("activityFilters"), "课外活动库应使用独立于资格条件的活动筛选状态。");
assert.ok(script.includes("journalFilters"), "国际期刊汇总应使用独立于项目资格条件的期刊筛选状态。");
assert.ok(script.includes("renderResourceFilterSnapshot"), "资源库应根据当前筛选更新摘要和结果数。");
assert.ok(script.includes("setResourceFilterCollapsed"), "资源库应控制高级筛选折叠状态。");
assert.ok(script.includes("trackResourceUsageEvent"), "资源库应记录关键筛选和加载行为。");
assert.ok(script.includes("resource_filter_applied"), "资源库应记录筛选条件应用。");
assert.ok(script.includes("resource_load_more"), "资源库应记录加载更多资源。");
assert.ok(styles.includes(".resource-combobox-toggle"), "论文方向按钮应有和普通筛选框一致的控件样式。");
assert.ok(styles.includes(".resource-results-console"), "资源库应有固定筛选摘要条样式。");
assert.ok(styles.includes(".resource-filter-pill"), "资源库应有已选条件 pill 样式。");
assert.ok(styles.includes("top: calc(100% + 6px)"), "论文方向菜单应固定从控件下方向下展开。");
assert.ok(styles.includes(".resource-combobox-menu .resource-combobox-option"), "论文方向菜单选项不应继承全局主按钮样式。");
assert.ok(script.includes("相关申请 / 报名要求"), "已排除项目应展示触发筛选的申请或报名要求。");
assert.ok(script.includes("<dt>简介</dt>"), "竞赛卡片应展示导入文档提供的项目简介。");
assert.ok(script.includes("<dt>报名 / 比赛时间</dt>"), "竞赛卡片应展示导入文档提供的时间字段。");
assert.ok(script.includes("<dt>活动亮点</dt>"), "课外活动卡片应展示活动亮点字段。");
assert.ok(!script.includes("参与方式待核实"), "卡片不应显示参与方式待核实标签。");
assert.ok(!script.includes("资格待核实"), "卡片不应显示资格待核实标签。");
assert.match(
  html,
  /id="clearResourceEligibility"[^>]*class="secondary"/,
  "清除筛选是普通辅助操作，不应采用危险按钮样式。",
);
